---
- name: Creates directory
  file:
    path: /var/lib/reserved-disk
    state: directory

- name: Reserve 10MB for ssh config
  command: "dd if=/dev/zero of=/var/lib/reserved-disk/ubuntu-ssh.img bs=1024 count=10k"
  args:
    creates: "/var/lib/reserved-disk/ubuntu-ssh.img"

- name: Create ext2 filesystem
  filesystem:
    fstype: ext2
    dev: /home/ubuntu/ssh.img
    
- name: Mount ssh config in homedir
  mount:
    path: /home/ubuntu/.ssh
    src: /home/ubuntu/ssh.img
    fstype: ext2
    state: mounted

- name: Set permissions for ssh config dir
  file:
    path: /home/ubuntu/.ssh
    owner: ubuntu
    group: ubuntu
    mode: '0700'

- name: Reserve 10MB for ssm
  command: "dd if=/dev/zero of=/var/lib/reserved-disk/ssm.img bs=1024 count=10k"
  args:
    creates: "/var/lib/reserved-disk/ssm.img"

- name: Create ext2 filesystem
  filesystem:
    fstype: ext2
    dev: /root/ssm.img

- name: Mount ssm
  mount:
    path: /var/lib/amazon/ssm
    src: /root/ssm.img
    fstype: ext2
    state: mounted

- name: Set permissions for ssm dir
  file:
    path: /var/lib/amazon/ssm
    owner: root
    group: root
    mode: '0700'
